apiVersion: apps/v1
kind: Deployment
metadata:
  name: albert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albert
  template:
    metadata:
      labels:
        app: albert
    spec:
      containers:
      - name: albert
        image: atulram4/coraculator-albert:1.2.0
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: albert-service
spec:
  selector:
    app: albert
  ports:
  - name: http
    port: 4000
