apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carrot
  template:
    metadata:
      labels:
        app: carrot
    spec:
      containers:
      - name: carrot
        env:
        - name: REDIS_HOST
          value: "redis-service.coraculator.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: PORT
          value: "5000"
        image: atulram4/coraculator-carrot:1.4.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: carrot-service
spec:
  selector:
    app: carrot
  ports:
  - name: http
    port: 5000
